[project]
name = "zmanim-blanks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet>=0.85.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "pyluach>=2.3.0",
    "zmanim>=0.3.1",
]

[project.scripts]
zmanim-blanks = "main:run"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
]

[build-system]
requires = ["uv_build>=0.11.16,<0.12"]
build-backend = "uv_build"
